spring:
  application:
    name: picngo

  mail:
    host: smtp.gmail.com
    port: 587
    username: ${MAIL_USERNAME}
    password: ${MAIL_PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  data:
    redis:
      host: ${REDIS_HOST:localhost}
      port: ${REDIS_PORT:6379}
      password: ${REDIS_PASSWORD:}

weather:
  api:
    key: ${WEATHER_SERVICE_KEY}

kakao:
  rest:
    api:
      key: ${KAKAO_REST_API_KEY}
  auth:
    user-info-url: https://kapi.kakao.com/v2/user/me

jwt:
  secret: ${JWT_SECRET}
  access-token-expiration-seconds: ${JWT_ACCESS_TOKEN_EXPIRATION_SECONDS:3600}


firebase:
  config:
    path: ${FIREBASE_CONFIG_PATH}
