CREATE TABLE `reports` (
  `id` bigint NOT NULL AUTO_INCREMENT,
  `target_type` enum('CHAT_MESSAGE','COMMENT','POST') NOT NULL,
  `target_id` bigint NOT NULL,
  `reporter_id` bigint NOT NULL,
  `reported_user_id` bigint NOT NULL,
  `reason` enum('ABUSE','COPYRIGHT','ETC','INAPPROPRIATE','SPAM') NOT NULL,
  `detail` varchar(500) DEFAULT NULL,
  `status` enum('DISMISSED','PENDING','RESOLVED') NOT NULL,
  `handled_by_id` bigint DEFAULT NULL,
  `handled_at` datetime(6) DEFAULT NULL,
  `resolution_note` varchar(1000) DEFAULT NULL,
  `target_content_snapshot` text NOT NULL,
  `created_at` datetime(6) DEFAULT NULL,
  `updated_at` datetime(6) DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_report_reporter_target` (`reporter_id`,`target_type`,`target_id`),
  KEY `idx_report_status_created_at` (`status`,`created_at`),
  KEY `idx_report_target` (`target_type`,`target_id`),
  KEY `idx_report_reported_user_created_at` (`reported_user_id`,`created_at`),
  KEY `idx_report_handled_by` (`handled_by_id`),
  CONSTRAINT `fk_report_reporter` FOREIGN KEY (`reporter_id`) REFERENCES `users` (`id`),
  CONSTRAINT `fk_report_reported_user` FOREIGN KEY (`reported_user_id`) REFERENCES `users` (`id`),
  CONSTRAINT `fk_report_handled_by` FOREIGN KEY (`handled_by_id`) REFERENCES `users` (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;
