-- V23, V24가 DB의 flyway_schema_history에는 기록되었으나 실제 로컬/운영 DB에 테이블이 생성되지 않은 환경을 위한 마이그레이션.
-- IF NOT EXISTS 구문으로 이미 테이블이 존재하는 환경에서는 안전하게 건너뜁니다.

CREATE TABLE IF NOT EXISTS `spot_accessibility_info` (
    `id` BIGINT NOT NULL AUTO_INCREMENT,
    `spot_id` BIGINT NOT NULL,
    `parking` TEXT NULL,
    `public_transport` TEXT NULL,
    `route` TEXT NULL,
    `ticket_office` TEXT NULL,
    `promotion` TEXT NULL,
    `wheelchair` TEXT NULL,
    `entrance_exit` TEXT NULL,
    `elevator` TEXT NULL,
    `restroom` TEXT NULL,
    `auditorium` TEXT NULL,
    `room` TEXT NULL,
    `physical_disability_etc` TEXT NULL,
    `braille_block` TEXT NULL,
    `help_dog` TEXT NULL,
    `human_guide` TEXT NULL,
    `audio_guide` TEXT NULL,
    `large_print` TEXT NULL,
    `braille_promotion` TEXT NULL,
    `guide_system` TEXT NULL,
    `visual_disability_etc` TEXT NULL,
    `sign_guide` TEXT NULL,
    `video_guide` TEXT NULL,
    `hearing_room` TEXT NULL,
    `hearing_disability_etc` TEXT NULL,
    `stroller` TEXT NULL,
    `lactation_room` TEXT NULL,
    `baby_chair` TEXT NULL,
    `infant_family_etc` TEXT NULL,
    `created_at` DATETIME(6) NOT NULL,
    `updated_at` DATETIME(6) NOT NULL,
    PRIMARY KEY (`id`),
    CONSTRAINT `uk_spot_accessibility_info_spot` UNIQUE (`spot_id`),
    CONSTRAINT `fk_spot_accessibility_info_spot` FOREIGN KEY (`spot_id`) REFERENCES `spot` (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE IF NOT EXISTS `spot_pet_info` (
    `id` BIGINT NOT NULL AUTO_INCREMENT,
    `spot_id` BIGINT NOT NULL,
    `accompany_type` VARCHAR(100) NULL,
    `allowed_companion` VARCHAR(255) NULL,
    `required_items` TEXT NULL,
    `additional_info` TEXT NULL,
    `facilities` TEXT NULL,
    `provided_items` TEXT NULL,
    `purchasable_items` TEXT NULL,
    `rental_items` TEXT NULL,
    `accident_risk_info` TEXT NULL,
    `created_at` DATETIME(6) NOT NULL,
    `updated_at` DATETIME(6) NOT NULL,
    PRIMARY KEY (`id`),
    CONSTRAINT `uk_spot_pet_info_spot` UNIQUE (`spot_id`),
    CONSTRAINT fk_spot_pet_info_spot FOREIGN KEY (`spot_id`) REFERENCES `spot` (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;
